# Generated by Django 2.0 on 2017-12-23 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('message_body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=4095)),
                ('latitude', models.DecimalField(decimal_places=9, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=9, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Service_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Service_Categories',
            },
        ),
        migrations.CreateModel(
            name='Service_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servusapp.Service')),
            ],
            options={
                'verbose_name_plural': 'Service_Images',
            },
        ),
        migrations.CreateModel(
            name='Service_Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_name', models.CharField(default='Base', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servusapp.Service')),
            ],
            options={
                'verbose_name_plural': 'Service_Prices',
            },
        ),
        migrations.CreateModel(
            name='Service_Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servusapp.Service')),
            ],
            options={
                'verbose_name_plural': 'Service_Times',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('site_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('i', 'in_progress'), ('e', 'error'), ('c', 'completed')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=4095)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('user_type', models.CharField(choices=[('p', 'provider'), ('c', 'consumer')], default='c', max_length=1)),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female'), ('o', 'other')], max_length=1)),
                ('birthdate', models.DateField()),
                ('profile_picture', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumer_transactions', to='servusapp.User'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_transactions', to='servusapp.User'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servusapp.Service'),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servusapp.Service_Category'),
        ),
        migrations.AddField(
            model_name='service',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servusapp.User'),
        ),
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_reviews', to='servusapp.User'),
        ),
        migrations.AddField(
            model_name='review',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_reviews', to='servusapp.User'),
        ),
        migrations.AddField(
            model_name='review',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servusapp.Service'),
        ),
        migrations.AddField(
            model_name='message',
            name='reciever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever_messages', to='servusapp.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_messages', to='servusapp.User'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='disputee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputee_disputes', to='servusapp.User'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='disputer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputer_disputes', to='servusapp.User'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servusapp.Service'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servusapp.Transaction'),
        ),
        migrations.AddField(
            model_name='booking',
            name='consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servusapp.User'),
        ),
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servusapp.Service'),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_time',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='servusapp.Service_Time'),
        ),
        migrations.AddField(
            model_name='booking',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servusapp.Transaction'),
        ),
    ]
